# Generated by Django 5.2.7 on 2026-09-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_question_question_type_quizresponse_materialprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_questions/%Y/%m/'),
        ),
    ]
