# Generated by Django 5.2.7 on 2026-09-11 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_question_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='manual_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='manual_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
